org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
# PCF project properties
mod_id=pcf
mod_name=ProxyCompatibleForge
description=Bring modern forwarding to Neo/Forge servers, requires the Ambassador plugin on Velocity for 1.13-1.20.1, should work standalone on 1.20.2+
group=org.adde0109.pcf
version=1.3.1
license=LGPL-2.1
authors=adde0109,JT122406,p0t4t0sandwich
java_version=25
homepage_url=https://github.com/adde0109/Proxy-Compatible-Forge#readme
repo_url=https://github.com/adde0109/Proxy-Compatible-Forge
issue_tracker_url=https://github.com/adde0109/Proxy-Compatible-Forge/issues
update_json_url=https://api.modrinth.com/updates/proxy-compatible-forge/forge_updates.json
# Forge/NeoForge specific
minecraft_version_range=[1.7.2,)
loader_version_range=[1,)
forge_version_range=[10,)
neo_version_range=[20.2,)
pack_format_number=4
